sys: Checkin generated bindings and make `bindgen` optional
Not all projects like or accept `bindgen` in their tree, primarily
because of requiring a full clang/LLVM install on the development
machine making things harder to just run and work out of the box.  At
the same time the bindings for this header are generic and do not need
to be regenerated unless the bindgen config in `build.rs` changes, or
the submodule is updated.

For these reasons, make `bindgen` optional behind a feature and test in
CI that the generated output doesn't change.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -201,3 +201,21 @@ jobs:
         env:
           RUSTDOCFLAGS: -Dwarnings
         run: cargo doc --workspace --no-deps --all-features --document-private-items
+
+  generate-bindings:
+    name: Generate nvngx-sys bindings
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout sources
+        uses: actions/checkout@v4
+        with:
+          submodules: true
+      - name: Clean
+        run: rm -rf crates/nvngx-sys/src/bindings.rs
+      - name: Install Vulkan SDK
+        if: ${{ runner.os == 'Linux' }}
+        run: sudo apt-get install libvulkan-dev
+      - name: Generate
+        run: cargo b -p nvngx-sys -F generate-bindings
+      - name: Diff generated Rust code
+        run: test -z "$(git status --porcelain)" || (echo "::error::Generated files are different, please regenerate with cargo build -F generate-bindings!"; git diff; false)
